### ISSUE TITLE
Plugin [id: 'com.github.hierynomus.jython', version: '0.1.0'] was not found

### ISSUE THREAD

**Issue by mcandre** [hierynomus/jython-gradle-plugin#1]
When I try to use the jython gradle plugin, I get:

```
Plugin [id: 'com.github.hierynomus.jython', version: '0.1.0'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Gradle Central Plugin Repository (no 'com.github.hierynomus.jython' plugin available - see https://plugins.gradle.org for available plugins)
```

I'm using Gradle 2.7, with `build.gradle`:

```
plugins {
  id 'com.github.hierynomus.jython' version '0.1.0'
}

apply plugin: 'com.github.hierynomus.jython'
```

**Comment by hierynomus** [comment]
Hi Andrew,

Just noticed that they changed their plugin portal some time ago. My other
plugin was listed there so I just assumed it would work.

For now please use the following:

apply plugin: 'jython' buildscript { repositories { jcenter() maven { url '
https://dl.bintray.com/hierynomus/gradle-plugins' } } dependencies {
classpath 'com.hierynomus.gradle.plugins:jython-gradle-plugin:0.1.0' }}
regards,
Jeroen

2015-09-25 20:28 GMT+02:00 Andrew Pennebaker notifications@github.com:

**Comment by hierynomus** [comment]
And now it's there :)

https://plugins.gradle.org/search?term=jython

Regards,
Jeroen

2015-09-25 22:51 GMT+02:00 Jeroen van Erp jeroen@javadude.nl:
