### ISSUE TITLE
Project does not use proxy when trying to activate the task "jythonDownload"

### ISSUE THREAD

**Issue by slbruce** [hierynomus/jython-gradle-plugin#15]
I am behind a corporate firewall.  As part of the jar task the jythonDownload task is called.  Even though the proxy is setup correctly in gradle.properties the plugin code does not use the proxy and always fails

### Expected Behavior
JythonDownload should use the proxy (either http or https) as defined in the gradle.properties file in the Gradle home directory and download the correct files.

### Current Behavior
```
9:59:38 AM: Executing external tasks 'clean jar'...
:clean
:compileJava UP-TO-DATE
:jythonDownload
Downloading Jython library: requests with version 2.13.0
:jythonDownload FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':jythonDownload'.
> javax.net.ssl.SSLHandshakeException: Received fatal alert: access_denied

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
```
It is important to note that other files that gradle needs to download are downloaded successfully.  It is when it comes to this resource - it fails.  It seems that the SSLSocket is not being passed the proxy information in this case

### Context
Trying to set up a gradle project.  It means that I cannot perform any task from behind the corporate firewall since this task "jythonDownload" is blocked because it does not utilise the proxy correctly.

### Steps to Reproduce (for bugs)
Trying to build this project: [https://github.com/xebialabs-community/xlr-hpe-alm-octane-plugin](https://github.com/xebialabs-community/xlr-hpe-alm-octane-plugin)
I have added the correct gradle.properties to my home directory, to the directory of the project and as system properties to the gradle build.

### Your Environment
Grunt 2.13
Happens on both Windows 10 and Linux CentOS machines
Proxy is correctly set in properties
[grade.output.txt](https://github.com/gradle/gradle/files/1006841/grade.output.txt)

**Comment by hierynomus** [comment]
Hi @slbruce,

I assume you've set the following properties for setting up the proxy:

```
systemProp.http.proxyHost=www.somehost.org
systemProp.http.proxyPort=8080
systemProp.http.proxyUser=userid
systemProp.http.proxyPassword=password
systemProp.http.nonProxyHosts=*.nonproxyrepos.com|localhost
```

(Or the corresponding https ones)...

I think they're not used because we're using another library for downloading the dependencies, as we could not easily leverage the dependency download mechanism of gradle.

I should be able to quickly fix this.

**Comment by hierynomus** [comment]
Could you give the current master a spin to see whether that fixes your issue?
If so, I'll release a new version.

**Comment by slbruce** [comment]
Hi @hierynomus 

Yes - I have the same issue with the latest version as well.  I had already added the proxy information in the gradle.properties file.

From the debugging that I was able to do I could see that the internal Socket that is opened to download the jython code does not use the proxy.  Even if the proxy is set as a system parameter it is seemed to be ignored

**Comment by hierynomus** [comment]
@slbruce Please try 0.8.0, it should have this fixed.

**Comment by hierynomus** [comment]
If not, feel free to reopen :)
