### ISSUE TITLE
PythonDependency not compatible with Gradle 4.9

### ISSUE THREAD

**Issue by vmj** [hierynomus/jython-gradle-plugin#20]
Hi,

it's extending an internal class that was still there in Gradle 4.8.1, but got moved (and somewhat refactored) in Gradle 4.9. So, on Gradle 4.9, whenever a build is using 'python(Object, Closure)' ḿethod, the build fails at configuration time.

I can take a look at fixing this if it is easy to do, but do you have any thoughts on this?

**Comment by hierynomus** [comment]
I'm fine with upgrading to the latest gradle version. I don't think it should be too hard to fix.

**Comment by vmj** [comment]
Thanks for the reply!

Just making sure we're on same page: compiling with 4.9 will make the plugin unusable for any lower version.

**Comment by hierynomus** [comment]
Yes, we will need to document that new versions are 4.9+ compatible and the existing versions up until 4.8.1
