### ISSUE TITLE
PyPi repository support for Nexus / Artifactory using Simple API instead of JSON API

### ISSUE THREAD

**Issue by ffung** [hierynomus/jython-gradle-plugin#22]
PyPi repositories hosted on Nexus or Artifactory (https://www.jfrog.com/jira/browse/RTFACT-16101) unfortunately don't support the PyPi JSON API; they only support the Simple API.  

I suggest rewriting `PypiRepository` to use the Simple API to query/download for dependencies, this is supported for Nexus, Artifactory and pypi.org.

I can open a PR if this is agreeable.

**Comment by hierynomus** [comment]
Hi Fai!
Feel free

**Comment by hierynomus** [comment]
Merged!
