### ISSUE TITLE
jython-gradle-plugin 0.9.0 broken upload

### ISSUE THREAD

**Issue by ffung** [hierynomus/jython-gradle-plugin#25]
https://plugins.gradle.org/m2/gradle/plugin/com/hierynomus/gradle/plugins/jython-gradle-plugin/0.9.0/jython-gradle-plugin-0.9.0.jar

is broken
```
<?xml version="1.0" encoding="UTF-8"?>
<Error>
    <Code>NoSuchKey</Code>
    <Message>The specified key does not exist.</Message>
    <Key>gradle.plugin.com.hierynomus.gradle.plugins/jython-gradle-plugin/0.9.0/3569c3949cde84fa3514912efac69823dca350ee35578acc5d14e87e5dc5f306/jython-gradle-plugin-0.9.0.jar</Key>
    <RequestId>903E36C14D471B53</RequestId>    
    <HostId>SUMult2R8Jt+XvGTjcauvXLp3VV7Da+7rcEEwNyzIMoLYwIvh0+JVUY5yoCahTS0qplH1DTOzKc=</HostId>
</Error>
```

This is a known issue with older versions of the plugin-publish plugin
https://discuss.gradle.org/t/plugin-authors-please-use-the-latest-plugin-publish-plugin-others-may-result-in-a-broken-upload/23573

**Comment by ffung** [comment]
@hierynomus Can we publish a new version of the plugin?

**Comment by hierynomus** [comment]
v0.10.0 released. Try that one!

**Comment by ffung** [comment]
yep works, thanks!
