### ISSUE TITLE
Example fails with ClassNotFoundException: org.apache.http.HttpResponse

### ISSUE THREAD

**Issue by diogocp** [hierynomus/jython-gradle-plugin#7]
Using the example build.gradle in the README:

``` gradle
plugins {
    id "java"
    id "com.github.hierynomus.jython" version "0.3.0"
}

dependencies {
  jython ":boto3:1.1.3"
}
```

```
$ gradle build
:compileJava UP-TO-DATE
:jythonDownload
Downloading Jython library: boto3 with version 1.1.3
:jythonDownload FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':jythonDownload'.
> org/apache/http/HttpResponse
```

The exception is: `java.lang.ClassNotFoundException: org.apache.http.HttpResponse`.

System:
- Arch Linux 4.6.2-1-ARCH amd64
- Gradle 2.13
- openjdk version "1.8.0_92"

**Comment by hierynomus** [comment]
You're right, thanks for reporting that. Seems like the newer versions of
Gradle are missing (parts of) HTTP components.

2016-06-12 0:51 GMT+02:00 Diogo Pereira notifications@github.com:

**Comment by diogocp** [comment]
@hierynomus can you make a release with the fix? I tried older versions of Gradle but ran into other problems.

**Comment by diogocp** [comment]
Please?

**Comment by hierynomus** [comment]
Sorry, this totally slipped my mind! Will release momentarily, thanks for reminding me.

**Comment by hierynomus** [comment]
[v0.3.1](https://plugins.gradle.org/plugin/com.github.hierynomus.jython) released.
